[package]
name = "focus"
version = "0.0.0"
edition = "2024"

[dependencies]
winit = "0.30"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
fontdue = "0.9"
gl = "0.14"
bstr = "1"
arboard = { version = "3", features = ["wayland-data-control"] }
similar = { version = "3", features = ["bytes"] }

[dev-dependencies]
png = "0.17"
gl = "0.14"
khronos-egl = { version = "6", features = ["dynamic"] }

[workspace]
members = [".", "hfuzz"]
