#!/usr/bin/env bash

set -ex

patchelf --set-interpreter $(cat $NIX_GCC/nix-support/dynamic-linker) zig-cache/focus-cross
patchelf --set-rpath $NIX_LIBGL_LIB/lib:$NIX_SDL2_LIB/lib zig-cache/focus-cross
scp ./zig-cache/focus-cross $FOCUS:/home/jamie/focus

scp ./shell.nix $FOCUS:/home/jamie/shell.nix

scp /home/jamie/exo-secret/memory.md $FOCUS:/home/jamie/exo-secret/memory.md
scp $FOCUS:/home/jamie/exo-secret/memory.log /home/jamie/exo-secret/memory.log
